# dynamic-testing-full.yml - testing for full pipeline (meant for dry runs)
#
# the following is a typical large-scale config (in this case which should
# closely match a subset of the v3.1 strats for GRCh38)

haploid_stratifications:
  GRCh38-full:
    ref:
      hap:
        url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta.gz
        md5: a6da8681616c05eb542f1d91606a7b2f
    strat_inputs:
      gap:
        bed:
          hap:
            url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/gap.txt.gz
            md5: 4880b2f4c3f08766003855818f0db02d
        params:
          bed_cols: {chr: 1, start: 2, end: 3}

      low_complexity:
        rmsk:
          bed:
            hap:
              url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
              md5: e8afed8cbcfef00b6cc47059c6fb6fa2
          params:
            bed_cols: {chr: 5, start: 6, end: 7}
          class_col: 11

        satellites: null

        simreps:
          bed:
            hap:
              url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
              md5: b0e801344ba654a5146a2ba3e9973462
          params:
            bed_cols: {chr: 1, start: 2, end: 3}

      xy:
        features: 
          x_bed:
            bed:
              hap:
                url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrX_genomic_features_GRCh38.bed
                md5: 94acda1d4358d30753422799152f4310
            level_col: 3
          y_bed:
            bed:
              hap:
                url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrY_genomic_features_GRCh38.bed
                md5: 770682734c41f5f7c1655adf1f986cb6
            level_col: 3
          xtr: true
          ampliconic: true
        x_par:
          start: [0, 2781479]
          end: [155701383, 156030895]
        y_par:
          start: [10001, 2781479]
          end: [56887902, 57217415]

      segdups:
        superdups:
          bed:
            hap:
              url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
              md5: 502e2b4dd6bf0cbd8dbdd9eb373aaa8e
          params:
            bed_cols: {chr: 1, start: 2, end: 3}

      functional:
        bed:
          hap:
            url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gff.gz
            md5: 6b657881c2c8d2d099a1c1749299538e
          chr_pattern:
            special:
              1: NC_000001.11
              2: NC_000002.12
              3: NC_000003.12
              4: NC_000004.12
              5: NC_000005.10
              6: NC_000006.12
              7: NC_000007.14
              8: NC_000008.11
              9: NC_000009.12
              10: NC_000010.11
              11: NC_000011.10
              12: NC_000012.12
              13: NC_000013.11
              14: NC_000014.9
              15: NC_000015.10
              16: NC_000016.10
              17: NC_000017.11
              18: NC_000018.10
              19: NC_000019.10
              20: NC_000020.11
              21: NC_000021.9
              22: NC_000022.11
              23: NC_000023.11
              24: NC_000024.10
        params:
          bed_cols: {chr: 0, start: 3, end: 4}

      mappability:
        unplaced_chr_patterns: ["^chrM$", "^chr[^_]+_[^_]+$"]

    builds:
      test-autosome:
        chr_filter: []
        include: {}
